### ISSUE TITLE
Link of thesis missing

### ISSUE THREAD

**Issue by leocob** [atmguille/archetypal-analysis#1]
Hi Guillermo,
Thank you for your implementation of the archetypal analysis in Python.
I was interested in reading your thesis but I'm afraid you didn't add the link. Could you upload it?

Thanks!
Best,
Leonardo

**Comment by atmguille** [comment]
Hi Leonardo,
Thanks for your interest. I've just uploaded the [original Thesis](https://github.com/atmguille/archetypal-analysis/blob/main/Thesis/%5BSpanish%5D%20Analisis%20de%20arquetipos%20y%20aplicaciones.pdf) (in Spanish) and an [English translation](https://github.com/atmguille/archetypal-analysis/blob/main/Thesis/%5BEnglish%5D%20Archetypal%20analysis%20and%20applications.pdf).
If it ends up being useful to your research, please consider citing our work.
Let me know if you need anything else!

**Comment by atmguille** [comment]
Hi Leonardo,
Thanks for your interest. Done, I've just uploaded the [original Thesis](https://github.com/atmguille/archetypal-analysis/blob/main/Thesis/%5BSpanish%5D%20Analisis%20de%20arquetipos%20y%20aplicaciones.pdf) (in Spanish) and an [English translation](https://github.com/atmguille/archetypal-analysis/blob/main/Thesis/%5BEnglish%5D%20Archetypal%20analysis%20and%20applications.pdf).
If it ends up being useful to your research, please consider citing our work.
Let me know if you need anything else!

**Comment by leocob** [comment]
Thank you Guillermo, I will of course cite your work if I'll end up using it!
